### ISSUE TITLE
Support for Ristretto family?

### ISSUE THREAD

**Issue by ThisIsMissEm** [WICG/webcrypto-secure-curves#12]
These build on Curve25519, but have some additional features — the Ristretto family is also useful in implementing the OPAQUE Secure Remote Password protocol.

Would ristretto255 be considered for inclusion? https://ristretto.group/

**Comment by twiss** [comment]
Hey :wave: I think this would be cool, but it may be a bit early for this. E.g., there's no RFC yet (I see that there's a [draft CFRG RFC](https://datatracker.ietf.org/doc/draft-irtf-cfrg-ristretto255-decaf448/), which is good, but it may be worth waiting until that's finalized. It's also not in TLS yet, for example, and I'm not sure if there would be implementer interest, in general. So I don't think we should add it now but it could always be added later, or in a separate document, if there's interest.

**Comment by ThisIsMissEm** [comment]
Okay, that works for me; I can use ristretto.js or a wasm implementation instead for now.

**Comment by ThisIsMissEm** [comment]
@twiss would it be a good idea to keep this open but label it as "Future" or something — you agreed it was a good idea?

**Comment by twiss** [comment]
Perhaps we could reconsider / reopen this when an RFC is released? Also, depending on the timing, I think it may make more sense to create a separate document for this by then (perhaps modeled after this one), if Curve25519 and Curve448 are already deployed, for example.
