### ISSUE TITLE
Quantum Resistant Algorithms

### ISSUE THREAD

**Issue by martinheidegger** [WICG/webcrypto-secure-curves#15]
Following the publication of NIST; would it be a good idea to expand this proposal to include quantum resistant algorithms here? https://www.nist.gov/news-events/news/2022/07/nist-announces-first-four-quantum-resistant-cryptographic-algorithms

**Comment by panva** [comment]
This draft only focuses on Curve25519 and Curve448. https://github.com/w3c/webcrypto would be a better fit to discuss PQ crypto algorithms inclusion and collect implementor's interest.

**Comment by martinheidegger** [comment]
Thank you for the redirect, but I seems I was a bit too overexcited still. It seems that it will take another 2 years until they become NIST standards and only then will find their way into OpenSSL and other suites.
