### ISSUE TITLE
The Ed25519 and Ed448 algorithm identifiers should be in capital letters 

### ISSUE THREAD

**Issue by javifernandez** [WICG/webcrypto-secure-curves#16]
All the algorithms defined in the [Web Cryptography API](https://w3c.github.io/webcrypto/#algorithm-overview) specification are defined in capital letters. Shouldn't the Ed25519 and Ed448 follow the same pattern ? 

As a matter of fact, Chrome implements an internal check to ensure this for the algorithms it implements from the WebCrypto spec.

**Comment by panva** [comment]
[RSASSA-PKCS1-v1_5](https://w3c.github.io/webcrypto/#rsassa-pkcs1).

The names also align with the crv values in JWK which are case-sensitive. 

They also align with how they're decribed in [RFC8032](https://www.rfc-editor.org/rfc/rfc8032.html#section-5.1). 

I guess what I'm trying to point at is that we've got the identifiers right.

**Comment by javifernandez** [comment]
Fair enough, I agree with the current naming make sense. 
Sorry for the noise.
