### ISSUE TITLE
Keypair for EdDSA Signing

### ISSUE THREAD

**Issue by armfazh** [WICG/webcrypto-secure-curves#18]
The signing procedure of EdDSA requires both the private and public keys. Of course, the public key can be derived from the private key, but it involves a non-trivial cost to pay.

The current signing interface accepts only the private key, does it make sense to pass a CryptoKeyPair object instead of a CryptoKey? 

```diff
const ed25519_key = await crypto.subtle.generateKey('Ed25519',true, ['sign', 'verify']);
const data = new TextEncoder().encode('Some message');
- const signature = await crypto.subtle.sign('Ed25519', ed25519_key.privateKey, data);
+ const signature = await crypto.subtle.sign('Ed25519', ed25519_key, data);
```

**Comment by twiss** [comment]
Yes, I agree, implementations are free to store the public key together with the private key, in fact that's quite common in Ed25519 libraries, I believe.

In addition, the current [WebIDL](https://w3c.github.io/webcrypto/#subtlecrypto-interface) for `sign` restricts us to accepting a `CryptoKey`, so I don't think we can change that to accepting a `CryptoKeyPair` very easily.

**Comment by steveluscher** [comment]
Additionally, libraries that accept _both_ keys create an opportunity for private key leakage if the implementer supplies or can be tricked into supplying the wrong public key: https://github.com/MystenLabs/ed25519-unsafe-libs?tab=readme-ov-file#what-is-the-issue
