### ISSUE TITLE
Dichotomy between verification equations for EdDSA

### ISSUE THREAD

**Issue by armfazh** [WICG/webcrypto-secure-curves#19]
The [Section 5.1.7](https://www.rfc-editor.org/rfc/rfc8032#section-5.1.7) of RFC-8032 specifies:

```
5.1.7 Verify 

 3.  Check the group equation [8][S]B = [8]R + [8][k]A'.  It's
     sufficient, but not required, to instead check [S]B = R + [k]A'.
```

which equation will be used? 
  :rocket: : `[h][S]B = [h]R + [h][k]A'`
  :heart: :  `[S]B = R + [k]A'`

**Comment by twiss** [comment]
The current draft doesn't specify which one should be used (which I guess you probably know, but just to be explicit) - is your opinion that we should pick one or the other?

I'm not sure if implementations will be able to pick very easily, they might be stuck with whatever their crypto library does. But it might be worth looking into what those commonly do, if every library does one of them, perhaps we can standardize on that.

**Comment by kayabaNerve** [comment]
Due to the above mentioned issue, I explicitly support this being locked down. Otherwise, browsers may disagree on signature validity.

I personally vote for the cheaper, non-cofactor clearing equation. Implementations, as a matter of policy, shouldn't generate torsioned keys in practice.

**Comment by kayabaNerve** [comment]
OpenSSL and BoringSSL both implement the non-cofactor clearing check.
