### ISSUE TITLE
Should importing a key that does not lie on the Ed25519 curve cause a runtime fatal?

### ISSUE THREAD

**Issue by steveluscher** [WICG/webcrypto-secure-curves#22]
The Solana network makes use of addresses (public keys) that lie _off_ the Ed25519 curve. The goal there is to create account addresses that take the form of 32-byte public keys, but that can't possibly have an associated private key (ie. nobody can sign on its behalf). Why you would want to do such a thing is not important, but just presume that there's a good reason and that the runtime support it.

Consider the following 32-byte public key that represents an address. This public key does not lie on the Ed25519 curve.

```
[0,121,240,130,166,28,199,78,165,226,171,237,100,187,247,95,50,251,221,83,122,255,247,82,87,237,103,22,201,227,114,153]
```

Those bytes import just fine:

```ts
// Tested in Node 18 and Safari 17
await crypto.subtle.importKey(
  'raw',
  new Uint8Array([0,121,240,130,166,28,199,78,165,226,171,237,100,187,247,95,50,251,221,83,122,255,247,82,87,237,103,22,201,227,114,153]),
  'Ed25519',
  false, /* extractable */
  ['verify'],
);
```

…but presumably that key is not useful for much, since it's not on the curve. No combination of arguments to `crypto.subtle.verify()` will ever yield anything but `false`.

Thoughts?

* Should importing such a key cause a runtime fatal?
* Should there be an `isOnCurve()` method?

**Comment by twiss** [comment]
Hello :wave: A similar question (about small-order elements) was discussed in #13, where I proposed rejecting those keys, but the consensus seemed to be that checks should happen during verification, e.g. see https://github.com/WICG/webcrypto-secure-curves/pull/13#issuecomment-1253336639. The current draft reflects that, i.e. the key should import but all verifications should fail.

> Should there be an `isOnCurve()` method?

What would be the use case of this? :relaxed:

**Comment by steveluscher** [comment]
> What would be the use case of this?

For sure, I can explain this.

There's a blockchain called Solana that uses Ed25519 keys and signatures. ‘Addresses’ of accounts and programs on the network correspond to 32-byte buffers, typically base58 encoded like this: `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`.

There are two kinds of addresses:

1. Addresses that correspond to the 32-bytes of an Ed25519 public key
2. Addresses that correspond to some _other_ 32-bytes of data

The first kind of address is necessarily associated with some Ed25519 private key. In this way, it's possible to sign on behalf of this address.

The second kind of address has no corresponding Ed25519 private key. This ensures that _nobody_ can sign on behalf of those addresses. This allows the runtime to reserve those addresses for special purposes. If you're interested in what exactly those purposes are, [here](https://docs.solana.com/developing/programming-model/calling-between-programs#program-derived-addresses) is the full rundown.

We have an `isOnCurve()` function in [userspace](https://github.com/solana-labs/solana-web3.js/blob/e36f58d2d0bbd36ff9ec7f421fb921f751499ee3/packages/addresses/src/curve.ts#L18-L24), but it would be lovely to be able to use the _native_ API to determine whether a point is on-curve or not (ie. a public key is valid or not).

**Comment by tniessen** [comment]
My understanding is that https://github.com/WICG/webcrypto-secure-curves/pull/21 already rejects off-curve points during verification (albeit not during import).

As far as I remember, some well-known cryptographers have spoken out against overzealous verification. In the context of Curve25519, Trevor Perrin wrote that such verification "is not needed in good protocols."

> Should there be an `isOnCurve()` method? (...) There's a blockchain called Solana

At this point, I personally don't think the Web Crypto API should target such niche use cases. The "major benefit" that is mentioned here is the ability to generate byte sequences that represent off-curve points, which is extremely uncommon.

**Comment by steveluscher** [comment]
Oh, I would hate for my ‘major benefit’ comment to be misunderstood. The benefit is not the _ability_ to generate byte sequences that represent off-curve points (which we can already do in userspace), the benefit of such a capability being elevated to the level of the JavaScript runtime is that:

* users no longer have to download the userspace implementation (sites load faster)
* one more supply chain risk is eliminated (eg. imagine that the implementation was an npm package that became compromised at some point)

It's already been a _huge_ win for runtimes to implement support for Ed25519; we've been able to shed double digit gzipped kilobytes from our applications now that the runtime itself can generate keys, sign messages, and verify signatures. The more capable the runtime, the fewer dependencies our applications have to take on.

**Comment by tniessen** [comment]
I understand your point. But it is still only meant to benefit a very niche use case. Users who wish to generate on-curve points can use existing Web Crypto APIs.

**Comment by steveluscher** [comment]
> A similar question (about small-order elements) was discussed in https://github.com/WICG/webcrypto-secure-curves/pull/13, where I proposed rejecting those keys, but the consensus seemed to be that checks should happen during verification, e.g. see https://github.com/WICG/webcrypto-secure-curves/pull/13#issuecomment-1253336639. The current draft reflects that, i.e. the key should import but all verifications should fail.

It's not my intention to bend the WebCrypto API to my niche use case. I was just hoping for _a_ way to use it to determine that a key is invalid or not, either explicitly or via inference. I don't think there is; even though the checks happen during verification, the WebCrypto API does not distinguish between ‘this failed because the signature is invalid’ and ‘this failed because the key you supplied is not a valid Ed25519 key.’

```ts
(async () => {
  const bytes = new Uint8Array(32); // Not a valid Ed25519 key
  const key = await crypto.subtle.importKey('raw', bytes, 'Ed25519', false, ['verify']); // Works
  console.log(
    // Always `false`, but why? Because the signature is invalid, or because the key is not an Ed25519 key?
    await crypto.subtle.verify('Ed25519', key, new Uint8Array(64), new Uint8Array([1, 2, 3])),
  );
})();
```

**Comment by twiss** [comment]
I personally agree that it would be nice if this was distinguishable, however, there are common Ed25519 libraries in which the result is indistinguishable, which is why it was made indistinguishable in this spec too; see https://github.com/WICG/webcrypto-secure-curves/pull/13#issuecomment-1359695558 and https://github.com/WICG/webcrypto-secure-curves/pull/21#issuecomment-1600427201. Changing that would complicate the implementation for runtimes using such libraries. And, to be perfectly honest, I also think this use case is a bit too niche to justify that.

**Comment by twiss** [comment]
I'll close this issue as the question in the title has been discussed in the linked PRs, and all signals (except at times from me) have been quite strongly against rejecting invalid keys on import. For better or worse, it's not something that's commonly done in Ed25519 implementations. Many libraries also don't support the functionality required for the `isOnCurve()` method you're suggesting, and this would also require extending the Web Crypto API surface, which would require considering other algorithms and is a bit of out of scope for this draft.

All in all, I think you're better off using a dedicated Ed25519 library that suits your needs :)

**Comment by steveluscher** [comment]
> …I think you're better off using a dedicated Ed25519 library that suits your needs

I respect your decision, but none the less – from the perspective of bundle size – we're worse off. The promise of being able to use JS built-ins implies that our customers no longer have to rely on userspace implementations that need to be downloaded, gunizpped, parsed, and JIT'd. We will have to ship [this `isOnCurve` implementation](https://github.com/solana-labs/solana-web3.js/blob/bb65ba9774d7bbd80d3b37a3c61c6342b83539b8/packages/addresses/src/vendor/noble/ed25519.ts) to our users forever.

¯\\_(°ペ)\_/¯

**Comment by tniessen** [comment]
@steveluscher I think the key point of this discussion is that, aside from the aforementioned niche use case, nobody has presented any convincing arguments for including this feature.

> I respect your decision, but none the less – from the perspective of bundle size – we're worse off.

Consider this perspective as well: if we were to add `isOnCurve` to the Web Crypto API and subsequently to every implementation of the Web Crypto API despite only a single project being interested in this, the vast majority of users would be worse off – from the perspective of software size.

**Comment by steveluscher** [comment]
> …the vast majority of users would be worse off – from the perspective of software size.

The browser/runtime binary would grow by one feature (one time cost) but each and every load of a website or script would shrink. Users experience performance penalties at each of these loads.
